---
- name: Update yum cache and install Nginx
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Create Nginx SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'
    owner: root
    group: root